### ISSUE TITLE
Let's integrate keygen.sh with the appropriate (test_server-HTTPS) tests.

### ISSUE THREAD

**Issue by zancas** [zingolabs/zecwalletlitelib#32] opened 2022-05-24 04:34 UTC

**Comment by zancas** [comment] 2022-05-24 04:35
I lost a little time trying to figure out why test_server tests started failing when I split into a `git worktree`

**Comment by AloeareV** [comment] 2022-05-24 15:37
Agree. I spent about 10-15 minutes looking into figuring out an idiomatic way to do this, when I first added the script. Will look more into this at some point later today, unless you beat me to it.

**Comment by AloeareV** [comment] 2022-05-24 19:33
Duplicate of #30

**Closed by AloeareV** 2022-05-24 19:33 UTC
